### ISSUE TITLE
Fails to load in JRuby: RangeError (bignum too big to convert into `long')

### ISSUE THREAD

**Issue by credbbl** [github/ssh_data#66]
This module expects in multiple locations that it can convert the special numbers 0 and 2^64-1 into a time stamp. This does not work in JRuby, where it uses a signed long to work on times.

```
irb(main):002:0> require "ssh_data"
Traceback (most recent call last):
       16: from org/jruby/RubyKernel.java:1052:in `load'
       15: from /usr/share/jruby/bin/irb:11:in `<main>'
       14: from org/jruby/RubyKernel.java:1237:in `catch'
       13: from org/jruby/RubyKernel.java:1237:in `catch'
       12: from org/jruby/RubyKernel.java:1507:in `loop'
       11: from org/jruby/RubyKernel.java:1091:in `eval'
       10: from (irb):2:in `evaluate'
        9: from /usr/share/jruby/lib/ruby/stdlib/rubygems/core_ext/kernel_require.rb:160:in `require'
        8: from org/jruby/RubyKernel.java:1017:in `require'
        7: from /var/lib/puppetserver/jruby-gems/gems/ssh_data-1.3.0/lib/ssh_data.rb:33:in `<main>'
        6: from /usr/share/jruby/lib/ruby/stdlib/rubygems/core_ext/kernel_require.rb:85:in `require'
        5: from org/jruby/RubyKernel.java:1017:in `require'
        4: from /var/lib/puppetserver/jruby-gems/gems/ssh_data-1.3.0/lib/ssh_data/certificate.rb:4:in `<main>'
        3: from /var/lib/puppetserver/jruby-gems/gems/ssh_data-1.3.0/lib/ssh_data/certificate.rb:5:in `<module:SSHData>'
        2: from /var/lib/puppetserver/jruby-gems/gems/ssh_data-1.3.0/lib/ssh_data/certificate.rb:8:in `<class:Certificate>'
        1: from org/jruby/RubyTime.java:1336:in `at'
RangeError (bignum too big to convert into `long')
```

**Comment by vcsjones** [comment]
Thanks for the report. This is an unfortunate behavior of jruby.

jruby's stance on this seems to be that it is an accepted and known incompatibility https://github.com/jruby/jruby/issues/1304.

Fixing this is a breaking change, as we could no longer return `Time.at((2**64)-1)` for `valid_before`. It's unlikely we would be able to address this any time soon as the bar for breaking changes in this repository is high, and GitHub does not use this gem in a jruby environment.

**Comment by credbbl** [comment]
Yeah, I imagined so much.

My fix would be to define marker objects representing those two special values, 0 and 2**64-1. They don't refer to real times, but are just approximated infinity. This is an incompatible API change if you consider the time values of infinity relevant and a compatible change if you expect people to use the existing constants.

**Comment by credbbl** [comment]
Well, would it be an acceptable change to just use this different behaviour on JRuby? No incompatible change, but a maintenance burden.
